server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
    druid:
      validation-query: select 1




mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lee.springcloud.com.lee.springcloud.entities


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: payment02
    prefer-ip-address: true
    #心跳检测时间间隔,单位为秒S,默认30秒
    lease-renewal-interval-in-seconds: 3
    #离上一次接收心跳检测后,经过的时间间隔后,将服务从eureka注册信息中删除,单位为秒S,默认90秒,该值至少要比lease-renewal-interval-in-seconds大
    lease-expiration-duration-in-seconds: 9
